#Script Name        :  newcheckoutconfigitem_dollar_price_as_string
#Description        :  This file have all the web elements/objects and page titles and URL's etc of new checkout project pages.   
#Author             :  NISUM Technologies              
#Reviewer           :  Ravi Gummala        
#Creation Date      :        
#Pre-conditions     :  Base environment, access to the Software Request System.
#Post-conditions:   :  Regression of the Software Request System based on functionality.
#Data Files         :  None at this level.
#******************************************************************************************************
# Revision History
#******************************************************************************************************
#Date               :                
#Revised By         :        
#******************************************************************************************************
#*********************************************************************************************

#********************************#### Shipping Page Web Elements ####*************************#
shipping_first_name: firstname
shipping_first_name_val: //input[@id='firstname']
shipping_last_name: lastname
shipping_last_name_val: //input[@id='lastName']
shipping_address_1: address1
shipping_address_1_val: //input[@id='address1']
shipping_address_2: address2
shipping_address_2_val: //input[@id='address2']
shipping_city: city 
shipping_city_val: //input[@id='city']
shipping_state_select: state 
shipping_state: //select[@id='state']
shipping_zipcode: zipcode 
shipping_zipcode_val: //input[@id='zipcode']
shipping_area_code: areacode
shipping_area_code_val: //input[@id='areacode']
shipping_exchange_nbr: exchangeNbr
shipping_exchange_nbr_val: //input[@id='exchangeNbr']
shipping_subscriber_nbr: subscriberNbr
shipping_subscriber_nbr_val: //input[@id='subscriberNbr']
shipping_international_shipping_link: //div[@id='anotherCountry']/div[2]/a
shipping_continue_checkout_btn: //input[@id='submit']
shipping_shippingMethod: //div[@id="deliveryMethod"]/fieldset[1]/ul[1]/li/span
shipping_everydayShippingMethod: //div[@id="deliveryMethod"]/fieldset[1]/ul[1]/li/input[@id="shipments0.shippingMethod.methodCode1"]
shipping_merchandise_total_in_shipping_page: //span[@id='subTotalAmount']
shipping_flat_tax_in_shipping_page: //li[@id='estimatedTax']
shipping_disabled_premium_shipping_method: //input[@id='shipments0.shippingMethod.methodCode2'][@disabled='disabled']
shipping_disabled_express_shipping_method: //input[@id='shipments0.shippingMethod.methodCode3'][@disabled='disabled']
shipping_error_message: //div[@class="removeErrorMessage left"]

payement:
shipping_first_name1: firstName
shipping_first_name1_val: //input[@id='firstName']
shipping_last_name1: lastName
shipping_last_name1_val: //input[@id='lastName']
shipping_address_11: addressLine1
shipping_address_11_val: //input[@id='addressLine1']
shipping_address_22: addressLine2
shipping_address_22_val: //input[@id='addressLine2']
shipping_city1: city 
shipping_city1_val: //input[@id='city']
shipping_state_select1: state 
shipping_state1: //select[@id='state']
shipping_zipcode1: zipCode 
shipping_zipcode1_val: //input[@id='zipCode']
shipping_area_code1: phoneAreaCode
shipping_area_code1_val: //input[@id='phoneAreaCode']
shipping_exchange_nbr1: phoneExchangeNBR
shipping_exchange_nbr1_val: //input[@id='phoneExchangeNBR']
shipping_subscriber_nbr1: phoneSubscriberNBR
shipping_subscriber_nbr1_val: //input[@id='phoneSubscriberNBR']
New_Default_Shipping details:
new_shipping_firstname: QA
new_shipping_lastname: Macys
new_shipping_address1: 685 Market Street
new_shipping_city: San Fransisco
new_shipping_state: California
new_shipping_zip_code: 94105
new_shipping_area_code: 123
new_shipping_exchange_code: 456
new_shipping_subscriber_code: 7890

Edit_Default_Shipping details:
edit_shipping_firstname: Automation
edit_shipping_lastname: QA
edit_shipping_address1: 685 Market Street
edit_shipping_city: San Fransisco
edit_shipping_state: California
edit_shipping_zip_code: 94103
edit_shipping_area_code: 567
edit_shipping_exchange_code: 234
edit_shipping_subscriber_code: 2940
state2: CA


#********************************#### Gift Options Web Elements ####*************************#
gift_option_no: //input[@id='giftNo']
gift_option_yes: //input[@id='giftYes']
gift_message_checkbox: //input[@id='addGiftMessage']
gift_message_textfield: //textarea[@id='giftMessage']
gift_box: //input[@id='giftOption']
gift_receipt: //input[@id='hidePrice']

#********************************#### Billing Page Web Elements ####*************************#
billing_credit_card_type: creditCardType
billing_card_number: cardNumber
billing_card_number_val: //*[@id="cardNumber"]
billing_expiration_month: expiration
billing_expiration_year: newCreditCard.creditCardExpiryYear
billing_security_code: abc
billing_security_code_val: //*[@id="abc"]
billing_sameasshippingaddress: useMyShippingAddress
billing_first_name: paymentFirstName
billing_first_name_val: //input[@id='firstName']
billing_last_name: paymentLastName
billing_last_name_val: //input[@id='lastName']
billing_address_1: paymentAddressLine1
billing_address_1_val: //input[@id='addressLine1']
billing_address_2: paymentAddressLine2
billing_address_2_val: //input[@id='paymentAddressLine2']
billing_city: paymentCity
billing_city_val: //input[@id='city']
billing_state: paymentState
billing_state_val: //*[@id='state']
billing_zipcode: paymentPostalCode
billing_zipcode_val: //input[@id='zipCode']
billing_contact_emailaddress: contactEmail
billing_contact_emailaddress_val: //input[@id='contactEmail']
billing_contact_emailaddress_verify: verifyEmail
billing_contact_emailaddress_verify_val: //*[@id="verifyEmail"]
billing_area_code: phoneArea
billing_area_code_val: //input[@id='phoneArea']
billing_exchange_nbr: exchangeNbr
billing_exchange_nbr_val: //input[@id='exchangeNbr']
billing_subscriber_nbr: subscriberNbr
billing_subscriber_nbr_val: //input[@id='subscriberNbr']
billing_continue_checkout_btn: //input[@id='submit']
billing_addcard_btn: //button[@id='addGiftCard']
billing_errormessage: fieldLevel
billing_create_profile_checkbox: createAccount
billing_create_profile_emailaddress: email
billing_create_profile_confirmemailaddress: confirmEmail
billing_create_profile_password: password
billing_create_profile_confirmpassword: cpassword
billing_create_profile_birthday: birthday_date
billing_create_profile_birthmonth: birthday_month
billing_create_profile_birthyear: birthday_year
billing_egc_cardnumber: //input[@id='addGiftCardEcardNumber'] 
billing_egc_captcha: //input[@id='addGiftCardCaptchaWord']
billing_egc_captcha_image: //img[@id='captchaImage']
billing_egc_addcard: //button[@id='overlayAddGiftCard']
billing_egc_newcaptcha: //img[@id='newImage']
billing_egc_cancel: //button[@id='cancel']
billing_egc_overlay_cancel: //img[@id='cancelBtn']
bread_crumbs: bread-crumbs

Billing_Default_Card details:
billing_new_card_type: Visa
billing_new_card_number: 4111111111111111
billing_new_card_securitycode: 123
billing_new_card_month: December
billing_new_card_year: 2014
edit_billing_email1: test@testing.com

New_Default_Billing details:
billing_new_firstname: QA
billing_new_lastname: Macys
billing_new_address1: 685 Market Street
billing_new_city: San Fransisco
billing_new_state: California
billing_new_zip_code: 94105
billing_new_area_code: 123
billing_new_exchange_code: 456
billing_new_subscriber_code: 7890

New Default Contact details:
billing_new_contact_emailaddress: QA@testmacys.com
edit_billing_new_contact_emailaddress: testing@testing.com

#********************************#### Order Review Page Web Elements ####*******************************#
order_review_contact_email: //div[@class='sectionPadding']/ul/li[3]/div[1]
order_review_phone: //div[@class='sectionPadding']/ul/li[3]/div[2]
order_review_place_order_btn: //*[@class='buttonSubmitBorders']
order_review_edit_shipping_details_btn: //*[@class='checkoutContainer shipAddr']
order_review_edit_payment_details_btn: //*[@class='checkoutContainer BillInfo']
order_review_edit_shipping_details_info: //*[@class='checkoutContainer shipAddr']
order_review_place_order: //*[@alt='PLACE ORDER']
order_review_edit_payment_details_info: //*[@class='checkoutContainer contInfo']
order_review_payment_details_info: //*[@class='OrderReview_billingAddress']/div
order_review_edit_payment_details: //*[@class="checkoutContainer BillInfo"]/a
#********************************#### Order Confirmation Page Web Elements ####*************************#
order_number: //div[@class='orderDetails']/span
order_total: //div[@class='orderTotal addCardShade']/div/span
order_confirmation_profile_email: //form[@id='confirmVB']/div/fieldset/div/div/span
order_confirmation_profile_shipping_address: //form[@id='confirmVB']/div/fieldset/div/div[2]/div

#********************************#### Checkout Page Web Elements, Titles and URLs ####****************#
checkout_signin_page_title: Sign In - Macy's Checkout
checkout_shipping_page_title : Shipping - Macy's Checkout
checkout_payment_page_title : Payment - Macy's Checkout
checkout_orderreview_page_title: Order Review - Macy's Checkout
checkout_orderconfirmation_page_title: Order Confirmation - Macy's
checkout_shipping_page_url: chkout/shipping
checkout_payment_page_url: chkout/payment
checkout_order_review_page_url: chkout/review
checkout_order_confirm_page_url: chkout/confirm
checkout_payment_errorpage_url: chkout/payment/continuecheckout
checkout_without_profile_btn: //*[@id='isWithoutProfile']
checkout_btn: //*[@alt="CONTINUE CHECKOUT"]

#********************************#### Header of Checkout Pages Web Elements ####************************#
header_macys_logo: //div[@id='header']/h1[@id='macysLogo']/a
header_macys_logo_fromPdp: //img[@alt="Macy's"]
header_chat: //a[@id='Live chat']
header_clicktocall: //a[@id='Click to call']
shoppingbag_icon: //a[@id='checkoutLink']

#********************************#### Footer of Checkout Pages Web Elements ####************************#
footer_shopwithconfidence_eassyretuns: //a[@id='easyReturnLink']
footer_shopwithconfidence_secureshopping: //a[@id='secureShoppingLink']
footer_shopwithconfidence_privacypolicy: //a[@id='privacyPolicyDetails']
footer_shopwithconfidence_shippingpolicy: //a[@id='ShippingPolicyDetails']

#********************************#### Mini Bag Web Elements, Titles and URLs ####********************#
mini_bag_promo_code: promoCodeValue
mini_bag_apply_promo_code: //button[@id='applyPromoCode']
mini_bag_remove_promo_code: //a[@id='removePromoCode']
mini_bag_shopping_bag_icon: //div[@id='iconShopbag']
mini_bag_bag_id_in_checkout_mini_bag: //span[@id='bagID']
mini_bag_order_total_in_mini_bag_on_shipping_page: //span[@id='totalAmount']
mini_bag_item_count: //span[@class='itemsCount']/span[@class='bold']
mini_bag_promotion_description: //label[@id='appliedPromoDesc']
mini_bag_promotion_price: //span[@id='appliedPromoPriceContainer']
mini_bag_container: //*[@class='globalMiniCartItems']
mini_bag_order_total: //span[@id='totalAmount']
mini_bag_sub_total: //span[@id='subTotalAmount']
mini_bag_shipping_cost: //span[@id='shippingCost']
mini_bag_you_saved: //span[@id='discountTotal']
mini_bag_remove_button: //div[@class='right removeFromBay']
shipping_surcharge_amount: //div[@id='bottom-panel']/ul/li[7]/span
personalized_fee_amount: //div[@id='bottom-panel']/ul/li[8]/span
sales_tax_amount: //div[@id='bottom-panel']/ul/li[10]
mini_product_image_link: //img[@class='upcPrimaryImage left']
tax: 0.06 

#********************************#### International Home Page Web Elements ####***********************#
international_home_page: internationalContext/index.ognc

#********************************#### PDP Web Elements ####*******************************************#
pdp_add_to_bag_btn: //img[@alt='add to bag']
pdp_atb_continue_checkout_btn: //img[@id='btnCheckout']
pdp_update_btn: //img[@id='updateButton']
pdp_sub_url: /shop/product?ID=
pdp_colorContainer: //div[@class='colors']
pdp_color: //div[@id='pdpAttributes']//div[@class='colors']/ul/li
pdp_size_available: //div[@id='pdpAttributes']/div[2]/div/ul/li[@class='horizontal size']
pdp_breadcrumbxpath1: //div[@class='#{bread_crumbs}']/a[1]
pdp_breadcrumbxpath2: //div[@class='#{bread_crumbs}']/a[2]

#********************************#### Shopping Bag Page Web Elements ####*****************************#
shopping_bag_page_url: shopping bag
shopping_bag_page_continue_checkout_btn: //div[@class='bagContainer shoppingButtons']//img[@alt='CONTINUE CHECKOUT']
shopping_bag_page_empty_error_msg: //div[@class='generalError']/div[@class='errorMsg']
shopping_bag_bag_id_in_shopping_bag: //div[@id='shoppingBagId']
shopping_bag_order_total_in_shopping_bag: //div[@id='bagTotal']
shopping_bag_order_total_currency_in_shopping_bag: //div[@id="bagTotalCurrency"]
shopping_bag_item_count_in_shopping_bag: //a[@class='globalMiniCartItems']
shopping_bag_merchandise_total_bag: //*[@name='merchTotal']
product_discount_price: //*[@id="bagYouSavedTotal"]
product_price: //*[@id="bagMerchandiseTotal"]
shopping_bag_id: //*[@class="orderSummary_bagid"] 
shopping_bag_promo_code_input: promoCodeValue
promo_code_value: promoCodeValue
apply_promo_code: applyPromoCode


Common Web Elements:
back_one_step_btn: //*[@alt='BACK ONE STEP'] 
price_sale: priceSale
checkout_in_popup: m_atb_checkout
class_bread_crumbs: breadCrumbs
text_you_are_in: You are in
bc_element: bcElement

Bread Crumbs:
bread_crumbs: bread-crumbs
class_bread_crumbs: breadCrumbs
text_you_are_in: You are in
bc_element: bcElement

promo code:
promo_code_value: promoCodeValue
apply_promo_code: applyPromoCode
enter_promo_code: FB20STK
promo_path: promoCode
promo_button_apply: //*[@id="applyPromoCode"]
price_value: //*[@id="bagTotal"]
promo_desc: //*[@class='promoRow']/div
promo_shipping_path: /html/body/div[3]/div[2]/div/div/div/form/div/div[2]/div/table/tbody/tr[4]/td
add_to_bag_btn: //*[@alt='add to bag']
merch_total_details: //*[@class="colTotal"]/span

Random:
xpath_mainmenus: //div[@id='globalNav']/ul/li/a/img
xpath_submenus: //div[@id='localNavigationContainer']/ul/li/ul/li/a
xpath_product_thumbnails: //div[@id='thumbnails']/div/div/div/a
xpath_product_thumbnails1: //div[@id='thumbnails1']/div/div/div/a
xpath_product_wethumbnails: //div[@id='weRecommendThumbnails']/div/div/div/a
xpath_color: //*[@id="pdpAttributes"]/div[@class="colors"]
xpath_color_val: //*[@id='pdpAttributes']/div[@class='colors']/ul/li
xpath_master_size: //*[@class="sizeSelection"]
xpath_master_size_val: //*[@class='sizeSelection']/div/div/ul/li
xpath_size: //*[@id="pdpAttributes"]/div[@class="sizes"]
xpath_size_val: //*[@id='pdpAttributes']/div/div/ul/li
updated_shipping_address: /html/body/div[5]/div[2]/div/div/div/form/div/div